[project]
name = "todo_app"
version = "1.0.0"
description = "A simple TO-DO List application built with Flask."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"